services:
  nginx:
    image: nginx
    ports: [8000:80]
    volumes: ["./nginx/nginx.conf:/etc/nginx/nginx.conf"]
  server1:
    build: ./server
    env_file:
      - ./server/.env
    environment:
      - SERVER="1st"
    ports: [5001:7000]
  server2:
    build: ./server
    env_file:
      - ./server/.env
    environment:
      - SERVER="2nd"
    ports: [5002:7000]
  server3:
    build: ./server
    env_file:
      - ./server/.env
    environment:
      - SERVER="3rd"
    ports: [5003:7000]
